<?php

$smoesjes = array(
									array("title" => "Ketting", "image" => "fotos/ketting.png", "text" => "Als je te laat wilt komen voor school omdat je nog even wilt spreken met een vriend of vriendin zijn dit de stappen die je moet volgen. Kom met de fiets naar school. Haal de ketting van je fiets en maak een foto van je ketting. Maak je handen wat vuil met smeer en je bent klaar om te laat op school te komen. Vergeet niet dat je niet meer dan 10/15 minuten te laat kan komen.", "categories" => array("school", "vrienden", "te laat", "ouders", "matige moeilijkheid", "alle")),
									array("title" => "Afwezig op school", "image" => "fotos/ziek.png", "text" => "De moeilijkheid van deze smoes hangt af van je geloofwaardigheid bij je ouders. Je zal ze namelijk moeten vertellen dat je last hebt van je maag of hoofd en dat je je niet kan concentreren. Als ze je geloven zorg je ervoor dat ze je school bellen en kan je thuis blijven.", "categories" => array("school", "afwezig", "ouders", "makkelijk", "alle")),
									array("title" => "Afwezig op school 2.0", "image" => "fotos/zwartelijst.png", "text" => "Deze smoes is er voor als je wilt spijbelen met je vrienden. Eerst moet je ervoor zorgen dat je de gsm's van je ouder in handen kan krijgen. Je zal de nummer van de school op de zwarte lijst moeten zetten en dan kan de school je ouders niet bellen. Dan ga je gewoon op tijd naar school maar ipv naar school te gaan ga je met je vrienden. Omdat de school je ouders niet kan bereiken zal je geen problemen krijgen met je ouders. Zal dan een briefje van je ouders moeten namaken of de b-code accepteren. De beslissing is aan jou.", "categories" => array("school", "ouders", "moeilijk", "afwezig", "alle"))
									array("title" => "Soep voor mama", "image" => "fotos/ziekemama.png", "text" => "Als je wilt uitslapen of een spel uitspelen, of je wilt je make-up afwerken nadat je laat bent opgestaan. Je vertelt gewoon je vriend/vriendin of leerkracht dat je moeder ziek is en dat je eten voor haar moest maken. Zo zorg je ervoor dat je medelijden krijgt in plaats van boosheid opdat je te laat kwam.")
);


?>